drop table if exists expense cascade;
drop table if exists settlement cascade;
drop table if exists users cascade;
drop table if exists user_settlement cascade;

create table users (user_id bigint generated by default as identity, nickname varchar(255), password varchar(255), username varchar(255), primary key (user_id));
create table settlement (owner_id bigint, settlement_id bigint generated by default as identity, name varchar(255), primary key (settlement_id));
create table user_settlement (settlement_id bigint, user_id bigint, user_settlement_id bigint generated by default as identity, primary key (user_settlement_id));
create table expense (expensed_date date, price numeric(38,2), expense_id bigint generated by default as identity, settlement_id bigint, user_id bigint, name varchar(255), primary key (expense_id));

alter table if exists expense add constraint fk_expense_users foreign key (user_id) references users;
alter table if exists expense add constraint fk_expense_settlement foreign key (settlement_id) references settlement on delete cascade;
alter table if exists settlement add constraint fk_settlement_owner foreign key (owner_id) references users on delete cascade;
alter table if exists user_settlement add constraint fk_user_settlement_settlement foreign key (settlement_id) references settlement on delete cascade;
alter table if exists user_settlement add constraint fk_user_settlement_users foreign key (user_id) references users;